import { initializeApp } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js";
import { getFirestore, collection, onSnapshot, addDoc, setDoc, getDoc, doc, updateDoc, deleteDoc, serverTimestamp, Timestamp, writeBatch } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js";
import { getAuth, signInWithEmailAndPassword, signOut, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js";
import { firebaseConfig } from "../firebase-config.js";

const app=initializeApp(firebaseConfig),db=getFirestore(app),auth=getAuth(app),$=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
let matches=[],players=[],opponents=[],events=[],media=[],albums=[],settings={},selectedMatchId="",currentAlbumId="",squadFilter="active";
let pendingPlayerPhoto="",editingPlayerPhoto="",pendingOpponentLogo="",editingOpponentLogo="",lineupXI=[],lineupBench=[];

$("#loginForm").addEventListener("submit",async e=>{e.preventDefault();const b=e.submitter;busy(b,true,"Signing in…");msg("#loginMessage","");try{await signInWithEmailAndPassword(auth,$("#email").value.trim(),$("#password").value);}catch(x){msg("#loginMessage",friendly(x),"error");}finally{busy(b,false,"Sign in");}});
$("#logoutBtn").addEventListener("click",()=>signOut(auth));
onAuthStateChanged(auth,u=>{$("#loginPanel").hidden=!!u;$("#dashboard").hidden=!u;$("#userEmail").textContent=u?.email||"—";$("#connectionBadge").textContent=u?"FIREBASE · AUTH":"FIREBASE";if(u)page("home");});

$("#adminNav").addEventListener("click",e=>{const b=e.target.closest("[data-page]");if(b)page(b.dataset.page);});
$$("[data-go]").forEach(b=>b.onclick=()=>page(b.dataset.go));
$$("[data-more]").forEach(b=>b.onclick=()=>{page("more");showTool(b.dataset.more);});
function page(n){$$("[data-page-panel]").forEach(p=>p.classList.toggle("active",p.dataset.pagePanel===n));$$("#adminNav [data-page]").forEach(b=>b.classList.toggle("active",b.dataset.page===n));$("#pageTitle").textContent=({home:"Home",matches:"Matches",squad:"Squad",more:"More"})[n]||"Club Hub";window.scrollTo({top:0,behavior:"smooth"});}
$$("[data-tool]").forEach(b=>b.onclick=()=>showTool(b.dataset.tool));
function showTool(n){$$(".tool-panel").forEach(x=>x.hidden=x.id!=="tool-"+n);setTimeout(()=>$("#tool-"+n)?.scrollIntoView({behavior:"smooth",block:"start"}),30);}
$$("[data-close]").forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close)?.close());

onSnapshot(collection(db,"matches"),s=>{matches=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>ms(b.kickoff)-ms(a.kickoff));renderMatches();overview();fillMatchSelects();counts();renderMatchdayHero();if(selectedMatchId){const exists=matches.some(m=>m.id===selectedMatchId);if(exists)refreshManager();else clearDeletedMatchState();}},e=>toast(friendly(e),"error"));
onSnapshot(collection(db,"players"),s=>{players=s.docs.map(d=>({id:d.id,...d.data()})).sort(playerSort);renderPlayers();fillPlayers();counts();if(selectedMatchId)renderLineup();},e=>toast(friendly(e),"error"));
onSnapshot(collection(db,"opponents"),s=>{opponents=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(a.name||"").localeCompare(b.name||""));renderOpponents();fillOpponents();counts();},e=>toast(friendly(e),"error"));
onSnapshot(collection(db,"events"),s=>{events=s.docs.map(d=>({id:d.id,...d.data()}));renderEvents();},e=>toast(friendly(e),"error"));
onSnapshot(collection(db,"media"),s=>{media=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(a.order??999)-(b.order??999)||stamp(b)-stamp(a));renderAlbums();renderAlbumPhotos();},e=>toast(friendly(e),"error"));
onSnapshot(collection(db,"albums"),s=>{albums=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>albumTime(b)-albumTime(a));renderAlbums();counts();if(currentAlbumId)refreshAlbum();},e=>toast(friendly(e),"error"));
onSnapshot(doc(db,"settings","public"),s=>{settings=s.exists()?s.data():{};applySettings();},()=>{});

function counts(){$("#countMatches").textContent=matches.length;$("#countPlayers").textContent=players.filter(p=>p.active!==false).length;$("#countOpponents").textContent=opponents.length;$("#countAlbums").textContent=albums.length;}
function renderMatchdayHero(){const m=matches.find(x=>["LIVE","HT","MATCHDAY"].includes(x.status));$("#matchdayHero").hidden=!m;if(!m)return;$("#matchdayHeroTitle").textContent="TEDU vs "+(m.opponent||"Opponent");$("#matchdayHeroMeta").textContent=(m.status||"MATCHDAY")+" · "+(m.venue||"Venue TBA")+" · "+date(m.kickoff);$("#openActiveMatchBtn").onclick=()=>openMatchManager(m.id);}
$("#quickNewMatch").onclick=openCreateMatch;$("#newMatchBtn").onclick=openCreateMatch;
function openCreateMatch(){$("#createMatchForm").reset();$("#createSeason").value=settings.currentSeason||String(new Date().getFullYear());$("#createType").value="Friendly Match";msg("#createMatchMessage","");$("#matchCreateDialog").showModal();}
$("#createMatchForm").addEventListener("submit",async e=>{e.preventDefault();const b=e.submitter,oid=$("#createOpponent").value,o=opponents.find(x=>x.id===oid),d=new Date($("#createKickoff").value);if(!o)return msg("#createMatchMessage","Choose opponent first.","error");if(Number.isNaN(d.getTime()))return msg("#createMatchMessage","Valid kick-off is required.","error");busy(b,true,"Saving…");try{const ref=await addDoc(collection(db,"matches"),{opponentId:o.id,opponent:o.name,opponentCode:o.code||"OPP",opponentLogo:o.logoData||"",opponentPrimary:o.primaryColor||"",opponentSecondary:o.secondaryColor||"",kickoff:Timestamp.fromDate(d),season:$("#createSeason").value.trim()||String(d.getFullYear()),matchday:Number($("#createMatchday").value)||null,matchType:$("#createType").value.trim()||"Friendly Match",venue:$("#createVenue").value.trim(),status:"UPCOMING",publicVisible:true,homeScore:0,awayScore:0,formation:"4-2-3-1",starters:[],substitutes:[],motmPlayerId:"",motmPlayerName:"",createdAt:serverTimestamp(),updatedAt:serverTimestamp()});$("#matchCreateDialog").close();toast("Match created ✓","ok");setTimeout(()=>openMatchManager(ref.id),100);}catch(x){msg("#createMatchMessage",friendly(x),"error");}finally{busy(b,false,"Save Match");}});

function overview(){const el=$("#overviewMatchList"),x=matches.slice(0,4);el.innerHTML=x.length?x.map(matchCard).join(""):'<div class="empty">No matches yet.</div>';bindMatchCards(el);}
function renderMatches(){const season=$("#adminSeasonFilter")?.value||"ALL",status=$("#adminStatusFilter")?.value||"ALL",list=matches.filter(m=>(season==="ALL"||String(m.season)===season)&&(status==="ALL"||m.status===status)),el=$("#matchAdminList");el.innerHTML=list.length?list.map(matchCard).join(""):'<div class="empty">No matches found.</div>';bindMatchCards(el);fillSeasons();}
function matchCard(m){const live=["LIVE","HT","FT"].includes(m.status),score=live?String(m.homeScore??0)+"–"+String(m.awayScore??0):"VS",logo=m.opponentLogo?'<img class="opp-logo" src="'+m.opponentLogo+'" alt="'+esc(m.opponent||"Opponent")+'">':'<div class="crest-placeholder">'+esc((m.opponentCode||"OP").slice(0,3))+'</div>';return '<article class="match-admin-card">'+logo+'<div class="match-main"><b>TEDU vs '+esc(m.opponent||"Opponent")+'</b><small>'+date(m.kickoff)+' · '+esc(m.venue||"Venue TBA")+' · '+esc(m.matchType||"Friendly")+'</small></div><div class="match-score">'+score+'<span>'+esc(m.status||"UPCOMING")+(m.publicVisible===false?" · HIDDEN":"")+'</span></div><div class="card-actions"><button data-manage="'+m.id+'">Manage</button><button class="'+(m.publicVisible===false?"":"public")+'" data-visible="'+m.id+'">'+(m.publicVisible===false?"Show":"Hide")+'</button><button class="danger" data-delete="'+m.id+'">Delete</button></div></article>';}
function bindMatchCards(root){root.querySelectorAll("[data-manage]").forEach(b=>b.onclick=()=>openMatchManager(b.dataset.manage));root.querySelectorAll("[data-visible]").forEach(b=>b.onclick=()=>toggleVisible(b.dataset.visible));root.querySelectorAll("[data-delete]").forEach(b=>b.onclick=()=>deleteMatch(b.dataset.delete));}
$("#adminSeasonFilter").onchange=renderMatches;$("#adminStatusFilter").onchange=renderMatches;
function fillSeasons(){const el=$("#adminSeasonFilter"),old=el.value||"ALL",ss=[...new Set(matches.map(m=>String(m.season||"")).filter(Boolean))].sort().reverse();el.innerHTML='<option value="ALL">All seasons</option>'+ss.map(s=>'<option value="'+esc(s)+'">'+esc(s)+'</option>').join("");el.value=ss.includes(old)?old:"ALL";}

function openMatchManager(id){const m=matches.find(x=>x.id===id);if(!m)return toast("This match no longer exists.","error");selectedMatchId=id;lineupXI=[...(m.starters||[])];lineupBench=[...(m.substitutes||[])];switchMatchTab("info");refreshManager();$("#matchManager").showModal();}
$("#closeMatchManager").onclick=()=>{$("#matchManager").close();selectedMatchId="";lineupXI=[];lineupBench=[];};
$$("[data-match-tab]").forEach(b=>b.onclick=()=>switchMatchTab(b.dataset.matchTab));
function switchMatchTab(n){$$("[data-match-tab]").forEach(b=>b.classList.toggle("active",b.dataset.matchTab===n));$$("[data-match-panel]").forEach(p=>p.classList.toggle("active",p.dataset.matchPanel===n));if(n==="poster")generatePoster();}
function refreshManager(){const m=matches.find(x=>x.id===selectedMatchId);if(!m)return;$("#managerTitle").textContent="TEDU vs "+(m.opponent||"Opponent");$("#managerMeta").textContent=date(m.kickoff)+" · "+(m.venue||"Venue TBA")+" · "+(m.matchType||"Friendly");$("#managerStatus").textContent=m.status||"UPCOMING";$("#managerVisibility").textContent=m.publicVisible===false?"HIDDEN":"PUBLIC";$("#managerVisibility").classList.toggle("hidden",m.publicVisible===false);fillMatchInfo(m);refreshLive(m);renderEvents();renderLineup();}
function fillMatchInfo(m){$("#editOpponent").value=m.opponentId||opponents.find(o=>(o.name||"").toLowerCase()===(m.opponent||"").toLowerCase())?.id||"";$("#editSeason").value=m.season||settings.currentSeason||"2026";$("#editMatchday").value=m.matchday||"";$("#editType").value=m.matchType||"Friendly Match";$("#editVenue").value=m.venue||"";$("#editStatus").value=m.status||"UPCOMING";$("#editMotm").value=m.motmPlayerId||"";$("#editHomeScore").value=m.homeScore??0;$("#editAwayScore").value=m.awayScore??0;$("#editFormation").value=m.formation||"4-2-3-1";if(m.kickoff?.toDate){const d=m.kickoff.toDate();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());$("#editKickoff").value=d.toISOString().slice(0,16);}}
$("#matchInfoForm").addEventListener("submit",async e=>{e.preventDefault();const b=e.submitter,id=selectedMatchId;if(!id)return;busy(b,true,"Saving…");try{const ref=doc(db,"matches",id),snap=await getDoc(ref);if(!snap.exists()){clearDeletedMatchState();return toast("This match has already been deleted.","error");}const oid=$("#editOpponent").value,o=opponents.find(x=>x.id===oid),d=new Date($("#editKickoff").value);if(!o)throw new Error("Choose opponent first.");if(Number.isNaN(d.getTime()))throw new Error("Valid kick-off is required.");const motm=$("#editMotm").value,mp=players.find(x=>x.id===motm);await updateDoc(ref,{opponentId:o.id,opponent:o.name,opponentCode:o.code||"OPP",opponentLogo:o.logoData||"",opponentPrimary:o.primaryColor||"",opponentSecondary:o.secondaryColor||"",kickoff:Timestamp.fromDate(d),season:$("#editSeason").value.trim()||String(d.getFullYear()),matchday:Number($("#editMatchday").value)||null,matchType:$("#editType").value.trim()||"Friendly Match",venue:$("#editVenue").value.trim(),status:$("#editStatus").value,homeScore:Math.max(0,Number($("#editHomeScore").value)||0),awayScore:Math.max(0,Number($("#editAwayScore").value)||0),motmPlayerId:motm||"",motmPlayerName:mp?.name||"",updatedAt:serverTimestamp()});msg("#matchInfoMessage","Saved ✓","ok");toast("Match saved ✓","ok");}catch(x){msg("#matchInfoMessage",friendly(x),"error");}finally{busy(b,false,"Save Changes");}});
$("#managerVisibility").onclick=()=>toggleVisible(selectedMatchId);
async function toggleVisible(id){const m=matches.find(x=>x.id===id);if(!m)return;try{await updateDoc(doc(db,"matches",id),{publicVisible:m.publicVisible===false,updatedAt:serverTimestamp()});toast(m.publicVisible===false?"Match is now public.":"Match hidden from public.","ok");}catch(x){toast(friendly(x),"error");}}
$("#deleteManagedMatch").onclick=()=>deleteMatch(selectedMatchId);
async function deleteMatch(id){const m=matches.find(x=>x.id===id);if(!m)return toast("Match already deleted.","error");if(!confirm("Delete TEDU vs "+(m.opponent||"Opponent")+"? Timeline events linked to this match will also be deleted."))return;try{const b=writeBatch(db);events.filter(e=>e.matchId===id).forEach(e=>b.delete(doc(db,"events",e.id)));b.delete(doc(db,"matches",id));await b.commit();if(selectedMatchId===id){$("#matchManager").close();selectedMatchId="";lineupXI=[];lineupBench=[];}toast("Match deleted ✓","ok");page("matches");}catch(x){toast(friendly(x),"error");}}
function clearDeletedMatchState(){selectedMatchId="";lineupXI=[];lineupBench=[];if($("#matchManager").open)$("#matchManager").close();toast("The match being edited was deleted. Editor has been reset.","error");}

function renderLineup(){const el=$("#lineupPlayerGrid");if(!el||!selectedMatchId)return;const active=players.filter(p=>p.active!==false||lineupXI.includes(p.id)||lineupBench.includes(p.id));el.innerHTML=active.map(p=>{const state=lineupXI.includes(p.id)?"xi":lineupBench.includes(p.id)?"bench":"none",photo=p.photoData?'<img src="'+p.photoData+'" alt="'+esc(p.name)+'">':'<span class="lineup-thumb">'+esc(initials(p.name))+'</span>';return '<button class="lineup-player" data-lineup-player="'+p.id+'" data-state="'+state+'">'+photo+'<b>#'+esc(p.number||"—")+' '+esc(p.name||"Player")+'</b><small>'+esc(p.position||"")+'</small></button>';}).join("");el.querySelectorAll("[data-lineup-player]").forEach(b=>b.onclick=()=>cycleLineup(b.dataset.lineupPlayer));updateLineupCounts();}
function cycleLineup(id){if(lineupXI.includes(id)){lineupXI=lineupXI.filter(x=>x!==id);lineupBench.push(id);}else if(lineupBench.includes(id)){lineupBench=lineupBench.filter(x=>x!==id);}else{if(lineupXI.length>=11)return toast("Starting XI already has 11 players.","error");lineupXI.push(id);}renderLineup();}
function updateLineupCounts(){$("#xiCount").textContent="Starting XI "+lineupXI.length+"/11";$("#benchCount").textContent="Bench "+lineupBench.length;}
$("#saveLineupBtn").onclick=async e=>{if(!selectedMatchId)return;busy(e.currentTarget,true,"Saving…");try{const ref=doc(db,"matches",selectedMatchId),snap=await getDoc(ref);if(!snap.exists())return clearDeletedMatchState();await updateDoc(ref,{starters:lineupXI,substitutes:lineupBench,formation:$("#editFormation").value||"4-2-3-1",updatedAt:serverTimestamp()});toast("Lineup saved ✓","ok");}catch(x){toast(friendly(x),"error");}finally{busy(e.currentTarget,false,"Save Lineup");}};

function refreshLive(m){$("#liveHomeScore").textContent=m.homeScore??0;$("#liveAwayScore").textContent=m.awayScore??0;$("#liveAwayCode").textContent=m.opponentCode||"OPP";}
$$("[data-score]").forEach(b=>b.onclick=async()=>{const m=matches.find(x=>x.id===selectedMatchId);if(!m)return toast("Choose a match first.","error");const [side,delta]=b.dataset.score.split(":"),k=side==="home"?"homeScore":"awayScore",n=Math.max(0,(Number(m[k])||0)+Number(delta));try{await updateDoc(doc(db,"matches",m.id),{[k]:n,updatedAt:serverTimestamp()});}catch(x){toast(friendly(x),"error");}});
$$("[data-status]").forEach(b=>b.onclick=async()=>{const m=matches.find(x=>x.id===selectedMatchId);if(!m)return;const st=b.dataset.status;if(st==="FT"&&!confirm("Set this match to Full Time?"))return;try{await updateDoc(doc(db,"matches",m.id),{status:st,updatedAt:serverTimestamp()});toast(st==="FT"?"Full Time saved ✓":st+" ✓","ok");}catch(x){toast(friendly(x),"error");}});
$("#eventForm").addEventListener("submit",async e=>{e.preventDefault();const m=matches.find(x=>x.id===selectedMatchId);if(!m)return msg("#liveMessage","Choose a match first.","error");const type=$("#eventType").value,team=$("#eventTeam").value,pid=$("#eventPlayer").value,sid=$("#eventSecondary").value,p=players.find(x=>x.id===pid),p2=players.find(x=>x.id===sid),ev={matchId:m.id,type,team,playerId:pid||"",playerName:p?.name||"",secondaryPlayerId:sid||"",secondaryPlayerName:p2?.name||"",minute:Number($("#eventMinute").value)||null,note:$("#eventNote").value.trim(),opponent:m.opponent||"",season:m.season||"",createdAt:serverTimestamp()};try{const ref=doc(collection(db,"events")),batch=writeBatch(db);batch.set(ref,ev);if(type==="GOAL"){const k=team==="home"?"homeScore":"awayScore";batch.update(doc(db,"matches",m.id),{[k]:(Number(m[k])||0)+1,status:"LIVE",updatedAt:serverTimestamp()});}await batch.commit();e.target.reset();$("#eventTeam").value="home";toast(type==="GOAL"?"GOAL recorded ⚽":"Event recorded ✓","ok");}catch(x){msg("#liveMessage",friendly(x),"error");}});
function renderEvents(){const el=$("#eventAdminList");if(!el)return;const list=events.filter(e=>e.matchId===selectedMatchId).sort((a,b)=>(a.minute??999)-(b.minute??999)||stamp(a)-stamp(b));el.innerHTML=list.length?list.map(e=>'<div class="event-row"><b>'+(e.minute?e.minute+"'":"—")+'</b><small>'+icon(e.type)+' '+esc(e.type||"EVENT")+'</small><div><b>'+esc(desc(e))+'</b><small>'+esc(e.note||"")+'</small></div><button data-delete-event="'+e.id+'">Delete</button></div>').join(""):'<div class="empty">No timeline events.</div>';el.querySelectorAll("[data-delete-event]").forEach(b=>b.onclick=()=>deleteEvent(b.dataset.deleteEvent));}
async function deleteEvent(id){const ev=events.find(x=>x.id===id);if(!ev||!confirm("Delete this event?"))return;try{const batch=writeBatch(db);batch.delete(doc(db,"events",id));if(ev.type==="GOAL"){const m=matches.find(x=>x.id===ev.matchId);if(m){const k=ev.team==="home"?"homeScore":"awayScore";batch.update(doc(db,"matches",m.id),{[k]:Math.max(0,(Number(m[k])||0)-1),updatedAt:serverTimestamp()});}}await batch.commit();toast("Event deleted.","ok");}catch(x){toast(friendly(x),"error");}}
function desc(e){if(e.type==="GOAL")return e.team==="home"?(e.playerName||"TEDU goal")+(e.secondaryPlayerName?" · Assist "+e.secondaryPlayerName:""):(e.note||e.opponent+" goal");if(e.type==="SUB")return(e.playerName||"Player out")+" → "+(e.secondaryPlayerName||"Player in");if(e.type==="YELLOW"||e.type==="RED")return e.team==="home"?(e.playerName||"TEDU"):(e.note||e.opponent);return e.note||e.playerName||"Match note";}
function icon(t){return({GOAL:"⚽",YELLOW:"🟨",RED:"🟥",SUB:"🔄",NOTE:"•"})[t]||"•";}

$$("[data-squad-filter]").forEach(b=>b.onclick=()=>{$$("[data-squad-filter]").forEach(x=>x.classList.remove("active"));b.classList.add("active");squadFilter=b.dataset.squadFilter;renderPlayers();});
function renderPlayers(){const el=$("#playerAdminList"),list=players.filter(p=>squadFilter==="all"||(squadFilter==="active"?p.active!==false:p.active===false));el.innerHTML=list.length?list.map(p=>'<button class="player-admin-card" data-edit-player="'+p.id+'"><div class="player-admin-photo">'+(p.photoData?'<img src="'+p.photoData+'" alt="'+esc(p.name)+'">':'<span>'+esc(initials(p.name))+'</span>')+'</div><div class="player-admin-copy"><b>#'+esc(p.number||"—")+' '+esc(p.name||"Player")+'</b><small>'+esc(p.position||"—")+'</small><em class="'+(p.active===false?"inactive":"")+'">'+(p.active===false?"ARCHIVED":"ACTIVE")+'</em></div></button>').join(""):'<div class="empty">No players in this list.</div>';el.querySelectorAll("[data-edit-player]").forEach(b=>b.onclick=()=>openPlayerEditor(b.dataset.editPlayer));}
$("#newPlayerBtn").onclick=()=>openPlayerEditor("");
function openPlayerEditor(id){const p=players.find(x=>x.id===id);$("#playerForm").reset();$("#playerId").value=p?.id||"";$("#playerDialogTitle").textContent=p?"Edit Player":"Add Player";$("#playerName").value=p?.name||"";$("#playerPosition").value=p?.position||"";$("#playerNumber").value=p?.number||"";$("#playerActive").value=String(p?.active!==false);editingPlayerPhoto=p?.photoData||"";pendingPlayerPhoto="";preview("#playerPhotoPreview",editingPlayerPhoto);$("#playerPhotoPlaceholder").style.display=editingPlayerPhoto?"none":"block";msg("#playerMessage","");$("#playerDialog").showModal();}
$("#playerPhotoFile").onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{toast("Compressing player photo…");pendingPlayerPhoto=await compress(f,720,.78,300000);preview("#playerPhotoPreview",pendingPlayerPhoto);$("#playerPhotoPlaceholder").style.display="none";toast("Player photo ready ✓","ok");}catch(x){toast(friendly(x),"error");}};
$("#removePlayerPhoto").onclick=()=>{pendingPlayerPhoto="__REMOVE__";editingPlayerPhoto="";$("#playerPhotoPreview").removeAttribute("src");$("#playerPhotoPlaceholder").style.display="block";};
$("#playerForm").addEventListener("submit",async e=>{e.preventDefault();const b=e.submitter,name=$("#playerName").value.trim(),position=$("#playerPosition").value.trim().toUpperCase();if(!name||!position)return msg("#playerMessage","Name and position are required.","error");const id=$("#playerId").value||slug(name),photo=pendingPlayerPhoto==="__REMOVE__"?"":pendingPlayerPhoto||editingPlayerPhoto||"";busy(b,true,"Saving…");try{await setDoc(doc(db,"players",id),{name,position,number:$("#playerNumber").value.trim(),active:$("#playerActive").value==="true",photoData:photo,updatedAt:serverTimestamp()},{merge:true});$("#playerDialog").close();toast("Player saved ✓","ok");}catch(x){msg("#playerMessage",friendly(x),"error");}finally{busy(b,false,"Save Player");}});

function renderOpponents(){const el=$("#opponentAdminList");el.innerHTML=opponents.length?opponents.map(o=>'<article class="opponent-card">'+(o.logoData?'<img src="'+o.logoData+'" alt="'+esc(o.name)+' logo">':'<div class="crest-placeholder">'+esc((o.code||"OP").slice(0,3))+'</div>')+'<h3>'+esc(o.name||"Opponent")+'</h3><small>'+esc(o.code||"")+'</small><div class="card-actions"><button data-edit-opponent="'+o.id+'">Edit</button><button class="danger" data-delete-opponent="'+o.id+'">Delete</button></div></article>').join(""):'<div class="empty">No opponents yet.</div>';el.querySelectorAll("[data-edit-opponent]").forEach(b=>b.onclick=()=>openOpponent(b.dataset.editOpponent));el.querySelectorAll("[data-delete-opponent]").forEach(b=>b.onclick=()=>deleteOpponent(b.dataset.deleteOpponent));}
$("#newOpponentBtn").onclick=()=>openOpponent("");
function openOpponent(id){const o=opponents.find(x=>x.id===id);$("#opponentForm").reset();$("#opponentId").value=o?.id||"";$("#opponentDialogTitle").textContent=o?"Edit Opponent":"Add Opponent";$("#opponentName").value=o?.name||"";$("#opponentCode").value=o?.code||"";$("#opponentPrimary").value=o?.primaryColor||"#d52b1e";$("#opponentSecondary").value=o?.secondaryColor||"#101010";editingOpponentLogo=o?.logoData||"";pendingOpponentLogo="";preview("#opponentLogoPreview",editingOpponentLogo);msg("#opponentMessage","");$("#opponentDialog").showModal();}
$("#opponentLogoFile").onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{pendingOpponentLogo=await compress(f,480,.8,190000);preview("#opponentLogoPreview",pendingOpponentLogo);toast("Logo ready ✓","ok");}catch(x){toast(friendly(x),"error");}};
$("#opponentForm").addEventListener("submit",async e=>{e.preventDefault();const b=e.submitter,name=$("#opponentName").value.trim(),code=$("#opponentCode").value.trim().toUpperCase();if(!name||!code)return;const id=$("#opponentId").value||slug(name),data={name,code,logoData:pendingOpponentLogo||editingOpponentLogo||"",primaryColor:$("#opponentPrimary").value,secondaryColor:$("#opponentSecondary").value,updatedAt:serverTimestamp()};busy(b,true,"Saving…");try{await setDoc(doc(db,"opponents",id),data,{merge:true});const rel=matches.filter(m=>m.opponentId===id);if(rel.length){const batch=writeBatch(db);rel.forEach(m=>batch.update(doc(db,"matches",m.id),{opponent:name,opponentCode:code,opponentLogo:data.logoData,opponentPrimary:data.primaryColor,opponentSecondary:data.secondaryColor,updatedAt:serverTimestamp()}));await batch.commit();}$("#opponentDialog").close();toast("Opponent saved ✓","ok");}catch(x){msg("#opponentMessage",friendly(x),"error");}finally{busy(b,false,"Save Opponent");}});
async function deleteOpponent(id){const o=opponents.find(x=>x.id===id);if(!o||!confirm("Delete "+o.name+" from opponent database? Existing matches keep their saved opponent details."))return;try{await deleteDoc(doc(db,"opponents",id));toast("Opponent deleted.","ok");}catch(x){toast(friendly(x),"error");}}

function renderAlbums(){const el=$("#albumAdminList");if(!el)return;el.innerHTML=albums.length?albums.map(a=>{const photos=media.filter(m=>m.albumId===a.id),cover=photos.find(p=>p.id===a.coverMediaId)||photos[0];return '<article class="album-admin-card">'+(cover?'<img style="width:100%;aspect-ratio:1.5;object-fit:cover;border-radius:12px" src="'+cover.imageData+'" alt="'+esc(a.title||"Album")+'">':'')+'<h3>'+esc(a.title||"Album")+'</h3><small>'+esc(a.category||"Club")+' · '+photos.length+' photos · '+(a.visible===false?"HIDDEN":"PUBLIC")+'</small><div class="card-actions"><button data-edit-album="'+a.id+'">Manage</button></div></article>';}).join(""):'<div class="empty">No albums yet.</div>';el.querySelectorAll("[data-edit-album]").forEach(b=>b.onclick=()=>openAlbum(b.dataset.editAlbum));}
$("#newAlbumBtn").onclick=()=>openAlbum("");
function openAlbum(id){const a=albums.find(x=>x.id===id);currentAlbumId=a?.id||"";$("#albumForm").reset();$("#albumId").value=a?.id||"";$("#albumDialogTitle").textContent=a?.title||"New Album";$("#albumTitle").value=a?.title||"";$("#albumCategory").value=a?.category||"Matchday";$("#albumMatch").value=a?.matchId||"";$("#albumDate").value=albumInputDate(a);$("#albumVisibilityBtn").textContent=a?.visible===false?"HIDDEN":"PUBLIC";$("#deleteAlbumBtn").hidden=!a;renderAlbumPhotos();$("#albumDialog").showModal();}
$("#closeAlbumDialog").onclick=()=>{$("#albumDialog").close();currentAlbumId="";};
$("#albumForm").addEventListener("submit",async e=>{e.preventDefault();const b=e.submitter,title=$("#albumTitle").value.trim();if(!title)return;busy(b,true,"Saving…");try{const id=$("#albumId").value||slug(title)+"-"+Date.now().toString().slice(-5),existing=albums.find(a=>a.id===id),d=$("#albumDate").value?Timestamp.fromDate(new Date($("#albumDate").value+"T12:00:00")):null;await setDoc(doc(db,"albums",id),{title,category:$("#albumCategory").value,matchId:$("#albumMatch").value||"",date:d,visible:existing?existing.visible!==false:true,createdAt:existing?.createdAt||serverTimestamp(),updatedAt:serverTimestamp()},{merge:true});currentAlbumId=id;$("#albumId").value=id;$("#albumDialogTitle").textContent=title;toast("Album saved ✓","ok");}catch(x){toast(friendly(x),"error");}finally{busy(b,false,"Save Album");}});
$("#albumVisibilityBtn").onclick=async()=>{if(!currentAlbumId)return;const a=albums.find(x=>x.id===currentAlbumId);if(!a)return;try{await updateDoc(doc(db,"albums",a.id),{visible:a.visible===false,updatedAt:serverTimestamp()});}catch(x){toast(friendly(x),"error");}};
$("#deleteAlbumBtn").onclick=async()=>{const a=albums.find(x=>x.id===currentAlbumId);if(!a||!confirm("Delete album "+a.title+" and all photos inside it?"))return;try{const batch=writeBatch(db);media.filter(m=>m.albumId===a.id).forEach(m=>batch.delete(doc(db,"media",m.id)));batch.delete(doc(db,"albums",a.id));await batch.commit();$("#albumDialog").close();currentAlbumId="";toast("Album deleted ✓","ok");}catch(x){toast(friendly(x),"error");}};
$("#albumPhotoFiles").onchange=async e=>{const files=[...(e.target.files||[])];if(!files.length)return;if(!currentAlbumId){toast("Save the album first before uploading photos.","error");e.target.value="";return;}const base=media.filter(m=>m.albumId===currentAlbumId).length;for(let i=0;i<files.length;i++){msg("#albumUploadProgress","Compressing "+(i+1)+"/"+files.length+"…");try{const imageData=await compress(files[i],1200,.68,185000);await addDoc(collection(db,"media"),{albumId:currentAlbumId,title:files[i].name.replace(/\.[^.]+$/,""),caption:"",imageData,visible:true,order:base+i,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});}catch(x){toast(friendly(x),"error");}}msg("#albumUploadProgress",files.length+" photo(s) uploaded ✓","ok");e.target.value="";};
function renderAlbumPhotos(){const el=$("#albumPhotoAdminList");if(!el)return;const list=media.filter(m=>m.albumId===currentAlbumId).sort((a,b)=>(a.order??999)-(b.order??999)||stamp(a)-stamp(b)),a=albums.find(x=>x.id===currentAlbumId);$("#albumPhotoCount").textContent=list.length+" photos";el.innerHTML=list.length?list.map((p,i)=>'<article class="photo-admin-card"><img src="'+p.imageData+'" alt="'+esc(p.title||"Photo")+'"><div><small>'+(a?.coverMediaId===p.id?"COVER · ":"")+"Photo "+(i+1)+'</small><button data-cover-photo="'+p.id+'">Cover</button><button data-up-photo="'+p.id+'">↑</button><button data-down-photo="'+p.id+'">↓</button><button data-delete-photo="'+p.id+'">Delete</button></div></article>').join(""):'<div class="empty">No photos yet.</div>';el.querySelectorAll("[data-cover-photo]").forEach(b=>b.onclick=()=>setAlbumCover(b.dataset.coverPhoto));el.querySelectorAll("[data-up-photo]").forEach(b=>b.onclick=()=>movePhoto(b.dataset.upPhoto,-1));el.querySelectorAll("[data-down-photo]").forEach(b=>b.onclick=()=>movePhoto(b.dataset.downPhoto,1));el.querySelectorAll("[data-delete-photo]").forEach(b=>b.onclick=()=>deletePhoto(b.dataset.deletePhoto));}
async function setAlbumCover(id){if(!currentAlbumId)return;try{await updateDoc(doc(db,"albums",currentAlbumId),{coverMediaId:id,updatedAt:serverTimestamp()});toast("Album cover updated.","ok");}catch(x){toast(friendly(x),"error");}}
async function movePhoto(id,dir){const list=media.filter(m=>m.albumId===currentAlbumId).sort((a,b)=>(a.order??999)-(b.order??999)||stamp(a)-stamp(b)),i=list.findIndex(x=>x.id===id),j=i+dir;if(i<0||j<0||j>=list.length)return;try{const batch=writeBatch(db);batch.update(doc(db,"media",list[i].id),{order:j,updatedAt:serverTimestamp()});batch.update(doc(db,"media",list[j].id),{order:i,updatedAt:serverTimestamp()});await batch.commit();}catch(x){toast(friendly(x),"error");}}
async function deletePhoto(id){if(!confirm("Delete this photo?"))return;try{const a=albums.find(x=>x.id===currentAlbumId),batch=writeBatch(db);batch.delete(doc(db,"media",id));if(a?.coverMediaId===id)batch.update(doc(db,"albums",a.id),{coverMediaId:"",updatedAt:serverTimestamp()});await batch.commit();}catch(x){toast(friendly(x),"error");}}
function refreshAlbum(){const a=albums.find(x=>x.id===currentAlbumId);if(!a)return;$("#albumVisibilityBtn").textContent=a.visible===false?"HIDDEN":"PUBLIC";renderAlbumPhotos();}

$("#settingsForm").addEventListener("submit",async e=>{e.preventDefault();const b=e.submitter,data={currentSeason:$("#settingCurrentSeason").value.trim()||"2026",showSquad:$("#settingShowSquad").checked,showStats:$("#settingShowStats").checked,showH2H:$("#settingShowH2H").checked,showMedia:$("#settingShowMedia").checked,showArchive:$("#settingShowArchive").checked,updatedAt:serverTimestamp()};busy(b,true,"Saving…");try{await setDoc(doc(db,"settings","public"),data,{merge:true});msg("#settingsMessage","Settings saved ✓","ok");}catch(x){msg("#settingsMessage",friendly(x),"error");}finally{busy(b,false,"Save settings");}});
function applySettings(){$("#settingCurrentSeason").value=settings.currentSeason||"2026";$("#settingShowSquad").checked=settings.showSquad!==false;$("#settingShowStats").checked=settings.showStats!==false;$("#settingShowH2H").checked=settings.showH2H!==false;$("#settingShowMedia").checked=settings.showMedia!==false;$("#settingShowArchive").checked=settings.showArchive!==false;}
$("#exportBackupBtn").onclick=()=>{const data={exportedAt:new Date().toISOString(),version:"2.0",matches:clean(matches),events:clean(events),opponents:clean(opponents),players:clean(players),albums:clean(albums),media:clean(media),settings:clean(settings)},blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download="tebakang-edu-club-hub-backup-"+new Date().toISOString().slice(0,10)+".json";a.click();URL.revokeObjectURL(u);};

function fillOpponents(){const opts=opponents.map(o=>'<option value="'+o.id+'">'+esc(o.name)+' ('+esc(o.code||"")+')</option>').join("");["#createOpponent","#editOpponent"].forEach(sel=>{const el=$(sel);if(!el)return;const old=el.value;el.innerHTML='<option value="">Choose opponent</option>'+opts;if(opponents.some(o=>o.id===old))el.value=old;});}
function fillPlayers(){const active=players.filter(p=>p.active!==false),opts=active.map(p=>'<option value="'+p.id+'">#'+esc(p.number||"—")+' '+esc(p.name)+' · '+esc(p.position||"")+'</option>').join("");["#editMotm","#eventPlayer","#eventSecondary"].forEach(sel=>{const el=$(sel);if(!el)return;const old=el.value;el.innerHTML='<option value="">Not selected</option>'+opts;if(active.some(p=>p.id===old))el.value=old;});}
function fillMatchSelects(){const opts=matches.map(m=>'<option value="'+m.id+'">'+date(m.kickoff)+' · TEDU vs '+esc(m.opponent||"Opponent")+'</option>').join("");$("#albumMatch").innerHTML='<option value="">None</option>'+opts;}

$("#generatePosterBtn").onclick=generatePoster;
$("#downloadPosterBtn").onclick=()=>{const canvas=$("#posterCanvas");canvas.toBlob(blob=>{if(!blob)return;const u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download="tebakang-edu-"+($("#posterType").value||"poster").toLowerCase()+"-"+new Date().toISOString().slice(0,10)+".png";a.click();URL.revokeObjectURL(u);},"image/png");};
async function generatePoster(){
  const m=matches.find(x=>x.id===selectedMatchId);if(!m)return;
  const type=$("#posterType").value,canvas=$("#posterCanvas"),x=canvas.getContext("2d"),W=canvas.width,H=canvas.height;await document.fonts.ready;x.clearRect(0,0,W,H);
  const g=x.createLinearGradient(0,0,W,H);g.addColorStop(0,"#03100b");g.addColorStop(.55,"#0b2118");g.addColorStop(1,"#030706");x.fillStyle=g;x.fillRect(0,0,W,H);x.globalAlpha=.1;x.strokeStyle="#29d17d";x.lineWidth=2;for(let i=-300;i<1400;i+=90){x.beginPath();x.moveTo(i,0);x.lineTo(i+700,H);x.stroke();}x.globalAlpha=1;x.fillStyle="#29d17d";x.fillRect(70,70,120,8);x.fillStyle="#efc75e";x.fillRect(W-190,70,120,8);
  const title=type==="FULLTIME"?"FULL TIME":type==="LINEUP"?"STARTING XI":type==="MOTM"?"MAN OF THE MATCH":"MATCHDAY";ct(x,title,W/2,150,"700 72px Oswald","center","#fff");ct(x,(m.matchType||"Friendly Match").toUpperCase(),W/2,205,"700 24px Inter","center","#9fb1a6");
  const club=await li("/assets/tebakang-edu-logo.webp"),opp=await li(m.opponentLogo||"/assets/katma-placeholder.svg");
  if(type==="MOTM"){const p=players.find(v=>v.id===m.motmPlayerId);if(p&&p.photoData){const ph=await li(p.photoData);cover(x,ph,120,300,840,620);x.fillStyle="rgba(3,8,6,.34)";x.fillRect(120,300,840,620);}contain(x,club,80,1040,120,120);ct(x,(p?.name||m.motmPlayerName||"NOT SELECTED").toUpperCase(),W/2,1010,"700 70px Oswald","center","#fff");ct(x,p?((p.position||"PLAYER")+" · #"+(p.number||"—")):"SELECT MOTM IN INFO",W/2,1070,"700 24px Inter","center","#29d17d");}
  else if(type==="LINEUP"){contain(x,club,70,260,150,150);contain(x,opp,W-220,260,150,150);ct(x,"TEBAKANG EDU",240,350,"700 34px Oswald","left","#fff");ct(x,(m.opponent||"OPPONENT").toUpperCase(),W-240,350,"700 34px Oswald","right","#fff");const xi=(m.starters||[]).map(id=>players.find(p=>p.id===id)).filter(Boolean);let y=510;xi.slice(0,6).forEach((p,i)=>{ct(x,String(i+1).padStart(2,"0")+"  "+p.name.toUpperCase(),130,y+i*95,"600 34px Oswald","left","#fff");ct(x,p.position||"",130,y+34+i*95,"700 16px Inter","left","#29d17d");});xi.slice(6).forEach((p,i)=>{ct(x,String(i+7).padStart(2,"0")+"  "+p.name.toUpperCase(),575,y+i*95,"600 34px Oswald","left","#fff");ct(x,p.position||"",575,y+34+i*95,"700 16px Inter","left","#29d17d");});}
  else{contain(x,club,105,325,300,300);contain(x,opp,W-405,325,300,300);ct(x,"TEBAKANG EDU",255,690,"700 42px Oswald","center","#fff");ct(x,(m.opponent||"OPPONENT").toUpperCase(),W-255,690,"700 42px Oswald","center","#fff");if(type==="FULLTIME")ct(x,String(m.homeScore??0)+"  —  "+String(m.awayScore??0),W/2,835,"700 122px Oswald","center","#fff");else ct(x,"VS",W/2,545,"700 80px Oswald","center","#efc75e");const kd=m.kickoff?.toDate?m.kickoff.toDate():null;if(kd){ct(x,kd.toLocaleDateString("en-MY",{day:"2-digit",month:"long",year:"numeric"}).toUpperCase(),W/2,type==="FULLTIME"?950:850,"700 30px Inter","center","#fff");if(type!=="FULLTIME")ct(x,kd.toLocaleTimeString("en-MY",{hour:"numeric",minute:"2-digit"}).toUpperCase(),W/2,900,"700 24px Inter","center","#9fb1a6");}ct(x,(m.venue||"VENUE TBA").toUpperCase(),W/2,type==="FULLTIME"?1005:960,"700 22px Inter","center","#9fb1a6");}
  ct(x,"KALAH BIASA, MENANG LUAR BIASA.",W/2,H-110,"700 22px Inter","center","#efc75e");ct(x,"TEBAKANG EDU CLUB HUB",W/2,H-70,"700 18px Inter","center","#8fa096");msg("#posterMessage","Poster generated. Download PNG when ready.","ok");
}
function ct(ctx,text,x,y,font,align,color){ctx.save();ctx.textAlign=align;ctx.fillStyle=color;ctx.font=font;ctx.fillText(text,x,y);ctx.restore();}
function li(src){return new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=()=>rej(new Error("Could not load poster image."));i.src=src;});}
function contain(ctx,img,x,y,w,h){const r=Math.min(w/img.width,h/img.height),nw=img.width*r,nh=img.height*r;ctx.drawImage(img,x+(w-nw)/2,y+(h-nh)/2,nw,nh);}
function cover(ctx,img,x,y,w,h){const r=Math.max(w/img.width,h/img.height),nw=img.width*r,nh=img.height*r;ctx.save();ctx.beginPath();ctx.rect(x,y,w,h);ctx.clip();ctx.drawImage(img,x+(w-nw)/2,y+(h-nh)/2,nw,nh);ctx.restore();}

async function compress(file,maxDim=700,q=.74,target=280000){if(!file.type.startsWith("image/"))throw new Error("Choose an image file.");const u=URL.createObjectURL(file);try{const im=await new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=()=>rej(new Error("Could not read image."));i.src=u;}),scale=Math.min(1,maxDim/Math.max(im.naturalWidth,im.naturalHeight)),w=Math.max(1,Math.round(im.naturalWidth*scale)),h=Math.max(1,Math.round(im.naturalHeight*scale)),c=document.createElement("canvas");c.width=w;c.height=h;c.getContext("2d").drawImage(im,0,0,w,h);let data=c.toDataURL("image/webp",q);while(data.length>target&&q>.36){q-=.07;data=c.toDataURL("image/webp",q);}if(data.length>700000)throw new Error("Image is still too large. Choose a smaller photo.");return data;}finally{URL.revokeObjectURL(u);}}
function preview(sel,src){const el=$(sel);if(!el)return;if(src)el.src=src;else el.removeAttribute("src");}
function busy(b,on,label){if(!b)return;b.disabled=on;if(on){b.dataset.oldLabel=b.textContent;b.textContent=label||"Saving…";}else b.textContent=b.dataset.oldLabel||label||"Save";}
function friendly(e){const c=e?.code||"",m=e?.message||"";if(c.includes("permission-denied"))return"Admin access is not permitted. Please sign in again.";if(c.includes("invalid-credential"))return"Email or password is incorrect.";if(c.includes("operation-not-allowed"))return"Email/Password sign-in is not enabled.";if(c.includes("resource-exhausted"))return"Firebase storage/quota limit was reached.";if(c.includes("unavailable")||c.includes("network")||m.toLowerCase().includes("network"))return"Internet connection is unstable. Please try again.";if(c.includes("not-found")||m.includes("No document to update"))return"This item was already deleted. The editor has been reset.";return m&&!m.includes("projects/")?m:"Something went wrong. Please try again.";}
function toast(text,type=""){const e=$("#globalToast");if(!e)return;e.textContent=text;e.className="global-toast "+type;e.hidden=false;clearTimeout(window.__toastTimer);window.__toastTimer=setTimeout(()=>e.hidden=true,4200);}
function msg(sel,text,type=""){const e=$(sel);if(e){e.textContent=text;e.className="message "+type;}}
function ms(t){return t?.toMillis?t.toMillis():new Date(t||0).getTime()||0;}function stamp(x){return x.createdAt?.toMillis?x.createdAt.toMillis():x.updatedAt?.toMillis?x.updatedAt.toMillis():0;}
function albumTime(a){return a.date?.toMillis?a.date.toMillis():stamp(a);}function albumInputDate(a){const d=a?.date?.toDate?a.date.toDate():a?.date?new Date(a.date):null;return d&&!Number.isNaN(d.getTime())?d.toISOString().slice(0,10):"";}
function date(t){const d=t?.toDate?t.toDate():t?new Date(t):null;return d&&!Number.isNaN(d.getTime())?d.toLocaleString("en-MY",{day:"2-digit",month:"short",year:"numeric",hour:"numeric",minute:"2-digit"}):"TBA";}
function playerSort(a,b){return(a.number||"999").localeCompare(b.number||"999",undefined,{numeric:true})||(a.name||"").localeCompare(b.name||"");}
function slug(s){return String(s||"").toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"item-"+Date.now();}
function initials(n=""){return n.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join("").toUpperCase()||"P";}
function esc(v=""){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function clean(v){if(v?.toDate)return v.toDate().toISOString();if(Array.isArray(v))return v.map(clean);if(v&&typeof v==="object"){const o={};Object.entries(v).forEach(a=>o[a[0]]=clean(a[1]));return o;}return v;}
